<a href="https://colab.research.google.com/github/luiscarp/Analisis_ENIF/blob/master/Entrenamiento.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Algoritmo KNN para la prediccion de exito de negocios en la ciudad de Chihuahua Mx**

In [ ]:

import pandas as pd

df = pd.read_csv("yearsclean.csv", index_col="PKid")

1. Calculo de duracion de proyectos

In [ ]:
ultimo_ano = df.groupby('id')['year'].max()
ultimo_ano

id
523593     2022
523595     2022
526404     2022
526867     2022
527086     2018
           ...
9390766    2022
9391239    2022
9391676    2022
9391889    2022
9391980    2022
Name: year, Length: 52489, dtype: int64

In [ ]:
duracion = ultimo_ano - df.groupby('id')['fecha_alta'].min()
duracion

id
523593     12
523595     12
526404     12
526867     12
527086      8
           ..
9390766     0
9391239     0
9391676     0
9391889     0
9391980     0
Length: 52489, dtype: int64

In [ ]:
duracion.to_csv("duraciones.csv")

In [ ]:
duracion_df = pd.DataFrame({'id': duracion.index, 'duracion': duracion.values})

In [ ]:
dfduracion = pd.merge(df, duracion_df, on='id')

In [ ]:
dfduracion.to_csv("datasetFinalNL.csv")

In [ ]:
dfduracion.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 252851 entries, 0 to 252850
Data columns (total 10 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   id          252851 non-null  int64
 1   nom_estab   252851 non-null  object
 2   nombre_act  252851 non-null  object
 3   per_ocu     252851 non-null  object
 4   cod_postal  248396 non-null  float64
 5   latitud     252851 non-null  float64
 6   longitud    252851 non-null  float64
 7   fecha_alta  252851 non-null  int64
 8   year        252851 non-null  int64
 9   duracion    252851 non-null  int64
dtypes: float64(3), int64(4), object(3)
memory usage: 21.2+ MB

In [ ]:
dfduracion.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 252851 entries, 0 to 252850
Data columns (total 10 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   id          252851 non-null  int64
 1   nom_estab   252851 non-null  object
 2   nombre_act  252851 non-null  object
 3   per_ocu     252851 non-null  object
 4   cod_postal  248396 non-null  float64
 5   latitud     252851 non-null  float64
 6   longitud    252851 non-null  float64
 7   fecha_alta  252851 non-null  int64
 8   year        252851 non-null  int64
 9   duracion    252851 non-null  int64
dtypes: float64(3), int64(4), object(3)
memory usage: 21.2+ MB

In [ ]:
dfduracion

,id,nom_estab,nombre_act,per_ocu,cod_postal,latitud,longitud,fecha_alta,year,duracion
0,607966,ABS MÉXICO,Servicios relacionados con la cría y explotaci...,11 a 30 personas,31215.0,28.639531,-106.103643,2010,2016,12
1,607966,ABS MÉXICO,Servicios relacionados con la cría y explotaci...,11 a 30 personas,31215.0,28.639531,-106.103643,2010,2017,12
2,607966,ABS MÉXICO,Servicios relacionados con la cría y explotaci...,11 a 30 personas,31215.0,28.639531,-106.103643,2010,2018,12
3,607966,ABS MÉXICO,Servicios relacionados con la cría y explotaci...,11 a 30 personas,31214.0,28.639531,-106.103643,2010,2019,12
4,607966,ABS MEXICO,Servicios relacionados con la cría y explotaci...,31 a 50 personas,31214.0,28.639531,-106.103643,2010,2020,12
...,...,...,...,...,...,...,...,...,...,...
252846,9389418,SONORA LABS,Laboratorios médicos y de diagnóstico del sect...,0 a 5 personas,31203.0,28.642266,-106.084492,2022,2022,0
252847,9389898,CERVECERIA ROMA,"Bares, cantinas y similares",51 a 100 personas,31125.0,28.715610,-106.147818,2022,2022,0
252848,9390766,NOMADA PARADERO GASTRONOMICO,Restaurantes con servicio de preparación de al...,11 a 30 personas,31000.0,28.635867,-106.076724,2022,2022,0
252849,9389899,SUBWEY,Restaurantes que preparan otro tipo de aliment...,6 a 10 personas,31125.0,28.699379,-106.131522,2022,2022,0
252850,9387612,MISTER LAVASOLAS,Lavanderías y tintorerías,0 a 5 personas,31064.0,28.605535,-106.027029,2022,2022,0

In [ ]:
dflimpio = dfduracion.drop_duplicates(subset='id')

In [ ]:
dfduracion.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 252851 entries, 0 to 252850
Data columns (total 10 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   id          252851 non-null  int64
 1   nom_estab   252851 non-null  object
 2   nombre_act  252851 non-null  object
 3   per_ocu     252851 non-null  object
 4   cod_postal  248396 non-null  float64
 5   latitud     252851 non-null  float64
 6   longitud    252851 non-null  float64
 7   fecha_alta  252851 non-null  int64
 8   year        252851 non-null  int64
 9   duracion    252851 non-null  int64
dtypes: float64(3), int64(4), object(3)
memory usage: 21.2+ MB

In [ ]:
dflimpio.to_csv("dfFINALlimpioCHECK2.csv")

In [ ]:
#USANDO AGRUPACIONES DE CLUSTERIZACION PARA REDUCIR DIMENSIONALIDAD
data = dflimpio[:]
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

# Imagina que 'datos' es tu DataFrame con una columna 'giro_negocio'
datos_limpieza = data['nombre_act'].str.lower().str.replace('[^\w\s]','')

# Tokenización y eliminación de palabras vacías
stop_words = stopwords.words('spanish')
datos_limpieza = datos_limpieza.apply(lambda x: ' '.join([word for word in x.split() if word not in (stop_words)]))

# TF-IDF
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(datos_limpieza)

# K-means Clustering
num_clusters = 100  # Ajusta este número según tus necesidades
km = KMeans(n_clusters=num_clusters)
km.fit(X)

# Obtener los clusters
clusters = km.labels_.tolist()

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
<ipython-input-214-fdb40bf33de6>:10: FutureWarning: The default value of regex will change from True to False in a future version.
  datos_limpieza = data['nombre_act'].str.lower().str.replace('[^\w\s]','')
/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

In [ ]:
dflimpio["giro"] = clusters

<ipython-input-215-62f7cddb3790>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dflimpio["giro"] = clusters

In [ ]:
dflimpio.to_csv("giroclusterFINN.csv")

In [ ]:
dflimpio

,id,nom_estab,nombre_act,per_ocu,cod_postal,latitud,longitud,fecha_alta,year,duracion,giro
0,607966,ABS MÉXICO,Servicios relacionados con la cría y explotaci...,11 a 30 personas,31215.0,28.639531,-106.103643,2010,2016,12,14
7,569965,"CAL NUTS, S. DE R.L. DE C.V.",Otros servicios relacionados con la agricultura,51 a 100 personas,31170.0,28.667444,-106.087900,2014,2016,4,14
10,6291843,SERVICIO CAMPESINA SA DE CV,Otros servicios relacionados con la agricultura,11 a 30 personas,31410.0,28.603297,-106.101424,2010,2016,8,14
13,607965,TECNOVET DE MÉXICO,Servicios relacionados con la cría y explotaci...,11 a 30 personas,31215.0,28.639564,-106.103636,2010,2016,12,14
20,6186120,AGNICO EAGLE MÉXICO,Minería de oro,251 y más personas,31217.0,28.623369,-106.111606,2010,2016,12,92
...,...,...,...,...,...,...,...,...,...,...,...
252846,9389418,SONORA LABS,Laboratorios médicos y de diagnóstico del sect...,0 a 5 personas,31203.0,28.642266,-106.084492,2022,2022,0,30
252847,9389898,CERVECERIA ROMA,"Bares, cantinas y similares",51 a 100 personas,31125.0,28.715610,-106.147818,2022,2022,0,38
252848,9390766,NOMADA PARADERO GASTRONOMICO,Restaurantes con servicio de preparación de al...,11 a 30 personas,31000.0,28.635867,-106.076724,2022,2022,0,39
252849,9389899,SUBWEY,Restaurantes que preparan otro tipo de aliment...,6 a 10 personas,31125.0,28.699379,-106.131522,2022,2022,0,43
252850,9387612,MISTER LAVASOLAS,Lavanderías y tintorerías,0 a 5 personas,31064.0,28.605535,-106.027029,2022,2022,0,20

In [ ]:
dflimpio["per_ocu"].value_counts()

0 a 5 personas        42848
6 a 10 personas        4452
11 a 30 personas       3449
31 a 50 personas        704
51 a 100 personas       482
101 a 250 personas      339
251 y más personas      215
Name: per_ocu, dtype: int64

In [ ]:
dflimpio["per_ocu"][dflimpio["per_ocu"] == '0 a 5 personas']=1
dflimpio["per_ocu"][dflimpio["per_ocu"] == '6 a 10 personas']=2
dflimpio["per_ocu"][dflimpio["per_ocu"] == '11 a 30 personas']=3
dflimpio["per_ocu"][dflimpio["per_ocu"] == '31 a 50 personas']=4
dflimpio["per_ocu"][dflimpio["per_ocu"] == '51 a 100 personas']=5
dflimpio["per_ocu"][dflimpio["per_ocu"] == '101 a 250 personas']=6
dflimpio["per_ocu"][dflimpio["per_ocu"] == '251 y más personas']=7

<ipython-input-219-5056d66bd49e>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dflimpio["per_ocu"][dflimpio["per_ocu"] == '0 a 5 personas']=1
<ipython-input-219-5056d66bd49e>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dflimpio["per_ocu"][dflimpio["per_ocu"] == '0 a 5 personas']=1
<ipython-input-219-5056d66bd49e>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dflimpio["per_ocu"][dflimpio["per_ocu"] == '6 a 10 personas']=2
<ipython-input-219-5056d66bd49e>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dflimpio["per_ocu"][dflimpio["per_ocu"] == '6 a 10 personas']=2
<ipython-input-219-5056d66bd49e>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dflimpio["per_ocu"][dflimpio["per_ocu"] == '11 a 30 personas']=3
<ipython-input-219-5056d66bd49e>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dflimpio["per_ocu"][dflimpio["per_ocu"] == '11 a 30 personas']=3
<ipython-input-219-5056d66bd49e>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dflimpio["per_ocu"][dflimpio["per_ocu"] == '31 a 50 personas']=4
<ipython-input-219-5056d66bd49e>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dflimpio["per_ocu"][dflimpio["per_ocu"] == '31 a 50 personas']=4
<ipython-input-219-5056d66bd49e>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dflimpio["per_ocu"][dflimpio["per_ocu"] == '51 a 100 personas']=5
<ipython-input-219-5056d66bd49e>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dflimpio["per_ocu"][dflimpio["per_ocu"] == '51 a 100 personas']=5
<ipython-input-219-5056d66bd49e>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dflimpio["per_ocu"][dflimpio["per_ocu"] == '101 a 250 personas']=6
<ipython-input-219-5056d66bd49e>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dflimpio["per_ocu"][dflimpio["per_ocu"] == '101 a 250 personas']=6
<ipython-input-219-5056d66bd49e>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dflimpio["per_ocu"][dflimpio["per_ocu"] == '251 y más personas']=7
<ipython-input-219-5056d66bd49e>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dflimpio["per_ocu"][dflimpio["per_ocu"] == '251 y más personas']=7

In [ ]:
dflimpio

,id,nom_estab,nombre_act,per_ocu,cod_postal,latitud,longitud,fecha_alta,year,duracion,giro
0,607966,ABS MÉXICO,Servicios relacionados con la cría y explotaci...,3,31215.0,28.639531,-106.103643,2010,2016,12,14
7,569965,"CAL NUTS, S. DE R.L. DE C.V.",Otros servicios relacionados con la agricultura,5,31170.0,28.667444,-106.087900,2014,2016,4,14
10,6291843,SERVICIO CAMPESINA SA DE CV,Otros servicios relacionados con la agricultura,3,31410.0,28.603297,-106.101424,2010,2016,8,14
13,607965,TECNOVET DE MÉXICO,Servicios relacionados con la cría y explotaci...,3,31215.0,28.639564,-106.103636,2010,2016,12,14
20,6186120,AGNICO EAGLE MÉXICO,Minería de oro,7,31217.0,28.623369,-106.111606,2010,2016,12,92
...,...,...,...,...,...,...,...,...,...,...,...
252846,9389418,SONORA LABS,Laboratorios médicos y de diagnóstico del sect...,1,31203.0,28.642266,-106.084492,2022,2022,0,30
252847,9389898,CERVECERIA ROMA,"Bares, cantinas y similares",5,31125.0,28.715610,-106.147818,2022,2022,0,38
252848,9390766,NOMADA PARADERO GASTRONOMICO,Restaurantes con servicio de preparación de al...,3,31000.0,28.635867,-106.076724,2022,2022,0,39
252849,9389899,SUBWEY,Restaurantes que preparan otro tipo de aliment...,2,31125.0,28.699379,-106.131522,2022,2022,0,43
252850,9387612,MISTER LAVASOLAS,Lavanderías y tintorerías,1,31064.0,28.605535,-106.027029,2022,2022,0,20

In [ ]:
dflimpio["per_ocu"] = dflimpio["per_ocu"].astype("category")

<ipython-input-221-481762dc3d0f>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dflimpio["per_ocu"] = dflimpio["per_ocu"].astype("category")

In [ ]:
dflimpio["duracion"] = dflimpio["duracion"].astype("category")

<ipython-input-222-3e7014485012>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dflimpio["duracion"] = dflimpio["duracion"].astype("category")

In [ ]:
dflimpio.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 52489 entries, 0 to 252850
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          52489 non-null  int64
 1   nom_estab   52489 non-null  object
 2   nombre_act  52489 non-null  object
 3   per_ocu     52489 non-null  category
 4   cod_postal  51026 non-null  float64
 5   latitud     52489 non-null  float64
 6   longitud    52489 non-null  float64
 7   fecha_alta  52489 non-null  int64
 8   year        52489 non-null  int64
 9   duracion    52489 non-null  category
 10  giro        52489 non-null  int64
dtypes: category(2), float64(3), int64(4), object(2)
memory usage: 4.1+ MB

In [ ]:
import pandas as pd
from sklearn.cluster import KMeans

# Cargar el archivo CSV


# Seleccionando solo las columnas latitud y longitud
coordenadas = dflimpio[['latitud', 'longitud']]

# Eliminando filas con valores NaN en estas columnas


# Ajustar el modelo KMeans
num_clusters = 100  # Número de clusters
kmeans = KMeans(n_clusters=num_clusters)

# Ajustar el modelo a los datos
kmeans.fit(coordenadas[['latitud','longitud']])

# Agregar las etiquetas de los clusters al DataFrame
dflimpio['cluster_ubicacion'] = kmeans.labels_

# Continúa con el análisis o visualización

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
<ipython-input-224-dd51de4c01b0>:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dflimpio['cluster_ubicacion'] = kmeans.labels_

In [ ]:
dflimpio.to_csv("Datapowerbi.csv")

In [ ]:
dflimpio["giro"] = dflimpio["giro"].astype("category")

<ipython-input-226-dce500dbb6c9>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dflimpio["giro"] = dflimpio["giro"].astype("category")

In [ ]:
df_one_hot = pd.get_dummies(dflimpio, columns=['giro'])

df_encoded = df_one_hot

In [ ]:
df_one_hot2 = pd.get_dummies(df_encoded, columns=['cluster_ubicacion'])

df_encoded = df_one_hot2

In [ ]:
df_encoded.to_csv("modeloEncodedUbiFIN.csv")

In [ ]:
df_encoded.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 52489 entries, 0 to 252850
Columns: 210 entries, id to cluster_ubicacion_99
dtypes: category(2), float64(3), int64(3), object(2), uint8(200)
memory usage: 13.7+ MB

In [ ]:
dfxencoded = df_encoded.drop(columns=["id", "nom_estab", "nombre_act", "cod_postal", "fecha_alta", "year", "latitud", "longitud"])

In [ ]:
dfxencoded.to_csv("encodedxUbi.csv")

In [ ]:
dfxencoded.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 52489 entries, 0 to 252850
Columns: 202 entries, per_ocu to cluster_ubicacion_99
dtypes: category(2), uint8(200)
memory usage: 10.5 MB

In [ ]:
x = dfxencoded.drop("duracion", axis=1)
y = dfxencoded[["duracion"]]

dfxencoded.drop("duracion", axis=1)

,per_ocu,giro_0,giro_1,giro_2,giro_3,giro_4,giro_5,giro_6,giro_7,giro_8,...,cluster_ubicacion_90,cluster_ubicacion_91,cluster_ubicacion_92,cluster_ubicacion_93,cluster_ubicacion_94,cluster_ubicacion_95,cluster_ubicacion_96,cluster_ubicacion_97,cluster_ubicacion_98,cluster_ubicacion_99
0,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
252846,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
252847,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
252848,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
252849,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
252850,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# 2. Cargar o crear un conjunto de datos
# Por ejemplo, vamos a usar el conjunto de datos de Iris incluido en scikit-learn
from sklearn.datasets import load_iris

X = x  # características
y = y.values.ravel()  # etiquetas

# 3. Dividir los datos en entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=54)

# 4. Crear el clasificador KNN y ajustarlo a los datos de entrenamiento
knn = KNeighborsClassifier(n_neighbors=5)  # Usar 3 vecinos para KNN
knn.fit(X_train, y_train)

# 5. Predecir las etiquetas para el conjunto de datos de prueba
y_pred = knn.predict(X_test)

# 6. Calcular y mostrar la precisión (accuracy) del modelo
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy del modelo KNN: {accuracy:.2f}")

Accuracy del modelo KNN: 0.30

In [ ]:
from joblib import dump

dump(knn, 'knn5100.joblib')